services:
  mongo:
    image: mongo:7
    container_name: bluboxx-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - bluboxx-mongo-data:/data/db

volumes:
  bluboxx-mongo-data: